### ISSUE TITLE
Camera image doesn't work

### ISSUE THREAD

**Issue by tanveer1302** [chavesgu/images_picker#1]
After selecting the camera option and clicking the picture, the confirm button on camera doesn't work and am unable to get camera image cause of it.

Also, can we have the option to:
1) Change the error message when the image limit is reached while selecting the media
2) Enable/disable preview mode while selecting the media.

**Comment by chavesgu** [comment]
@tanveer1302 please provide your code and logcat.it's work well on my device.

**Comment by tanveer1302** [comment]
> @tanveer1302 please provide your code and logs.it's work well on my device.what's your device type?

I used the example code without any changes. Everything opens till I open the camera. Once i click the picture with camera, the picture gets selected and all other options work fine i.e., retake and cancel ones. but the confirm/Ok button on the camera screen doesn't work at all.

import 'dart:io';

import 'package:flutter/material.dart';
import 'dart:async';

import 'package:flutter/services.dart';
import 'package:images_picker/images_picker.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  String _platformVersion = 'Unknown';
  String path;

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
        ),
        body: Column(
          children: [
            Text('Running on: $_platformVersion\n'),
            RaisedButton(
              child: Text('pick'),
              onPressed: ()async {
                List<Media> res = await ImagesPicker.pick(
                  count: 1,
                  pickType: PickType.video,
                  cropOpt: CropOption(),
                );
                if (res!=null) {
                  print(res[0]?.path);
                  setState(() {
                    path = res[0]?.thumbPath;
                  });
                }
              },
            ),
            RaisedButton(
              child: Text('openCamera'),
              onPressed: ()async {
                List<Media> res = await ImagesPicker.openCamera(
                  // pickType: PickType.video,
                );
                if (res!=null) {
                  print(res[0]?.path);
                 setState(() {
                   path = res[0]?.path;
                 });
                }
              },
            ),
            path!=null?Container(
              height: 200,
              child: Image.file(
                File(path),
                fit: BoxFit.contain,
              ),
            ):SizedBox.shrink(),
          ],
        ),
      ),
    );
  }
}

**Comment by chavesgu** [comment]
@tanveer1302  android or ios ?

**Comment by tanveer1302** [comment]
android

**Comment by chavesgu** [comment]
@tanveer1302  was pick api work well?

**Comment by tanveer1302** [comment]
works great. It would be great if you can provide some more customization to the pick UI e.g., custom Button Name, color, custom alert message, etc.

**Comment by chavesgu** [comment]
@tanveer1302  this is a new plugin, so implement important feature first. I will think your idea.
And I will check the bug you say above with camera

**Comment by tanveer1302** [comment]
thanks. But the alert message needs to be changed when user tries to select more than the defined limit. The message is not clear for the user and instead of "**Ok**" on the action for alert, it shows some message like "**I know the**".

For now can you please change the alert message to 

You can select maximum of $count images

and Instead of alert action "**I know the**", change it to "**Ok**"

**Comment by chavesgu** [comment]
@tanveer1302  I test open camera and take a photo, it did well. And I retake and cancel ones, camera is work well. My test phone is XIAOMI with andoird 8.

**Comment by thirtysixmm** [comment]
I could reproduce this issue. ImagesPicker.openCamera did not do anythig. So looked into the code tried the following code.
```

MethodChannel _channel = const MethodChannel('chavesgu/images_picker');

      List<dynamic> res = await _channel.invokeMethod('openCamera', {
        "pickType": PickType.image.toString(),
      });
```

The above code threw an exception

```
): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method openCamera on channel chavesgu/images_picker)
E/flutter (31143): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (31143): <asynchronous suspension>
E/flutter (31143): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (31143)
```

**Comment by chavesgu** [comment]
> I am facing the same issue. ImagesPicker.openCamera did not do anythig. So looked into the method implementation tried the following code.
> 
> ```
> 
> MethodChannel _channel = const MethodChannel('chavesgu/images_picker');
> 
>       List<dynamic> res = await _channel.invokeMethod('openCamera', {
>         "pickType": PickType.image.toString(),
>       });
> ```
> 
> The above code threw an exception
> 
> ```
> ): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method openCamera on channel chavesgu/images_picker)
> E/flutter (31143): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
> E/flutter (31143): <asynchronous suspension>
> E/flutter (31143): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
> E/flutter (31143)
> ```

what's your flutter version.
Show your flutter doctor

**Comment by thirtysixmm** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18363.900], locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

! Doctor found issues in 2 categories.

**Comment by chavesgu** [comment]
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18363.900], locale en-IN)
> [!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> X Android license status unknown.
> Run `flutter doctor --android-licenses` to accept the SDK licenses.
> See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
> [!] Android Studio (version 4.1.0)
> X Flutter plugin not installed; this adds Flutter specific functionality.
> X Dart plugin not installed; this adds Dart specific functionality.
> [√] Connected device (1 available)
> 
> ! Doctor found issues in 2 categories.

Can you just run example successfully?
