### ISSUE TITLE
An error occurred while calling the camera

### ISSUE THREAD

**Issue by jjva-xiao** [chavesgu/images_picker#10]
Hi, thanks for contributing this lib. With this library, I found in the Android 6.0.1 zte's camera phone call, a finished picture, click on the camera's ✅ no reaction, but if this time click ❎ can launch system normal camera back to the APP, because this is seen in the customer's phone, I can't provide the log, but I use the Android Studio simulator debugging of the ARM, also can simulate photos, But nothing ✅.

The development environment Flutter 1.22 Stable

Android builds the SDK API 29

Android Mini SDK API 21

You are using version 0.07 of your library

Looking forward your reply

**Comment by chavesgu** [comment]
我不太懂你的意思     我摊牌了  我是中国人

**Comment by jjva-xiao** [comment]
在安卓6.0系统的手机上，貌似拍照功能无法正常使用，具体表现为：进入相机之后拍照结束后，点击那个勾号，会没有任何反应，但是这个时候点击退出相机，也会正常退出，并且没有获取到图片

**Comment by chavesgu** [comment]
> 在安卓6.0系统的手机上，貌似拍照功能无法正常使用，具体表现为：进入相机之后拍照结束后，点击那个勾号，会没有任何反应，但是这个时候点击退出相机，也会正常退出，并且没有获取到图片

升级到`0.0.8`试试看 ， 我在云真机android 6 测试是可以了
