### ISSUE TITLE
How to change the button text after the images selection exceeds the count limit

### ISSUE THREAD

**Issue by Dudes-pr** [chavesgu/images_picker#11]
Hello , when a user select more images than the given limit. a pop shows which says "I know the" how can i change it? i have searched for it in the package but couldn't find it anywhere.

**Comment by chavesgu** [comment]
Firstly, this plugin focus on the realization of functionality.And this plugin use third-party lib for android or ios.So this plugin's configurations such as you say for ui will not provide
