### ISSUE TITLE
[iOS 12.2] Don't see Cancel button if user'd like to exit gallery with no image selected

### ISSUE THREAD

**Issue by Thaontt306** [chavesgu/images_picker#12]

**Comment by chavesgu** [comment]
![image](https://user-images.githubusercontent.com/20633606/108937984-39aaee80-768a-11eb-8b95-23d673c3076e.png)

**Comment by Thaontt306** [comment]
Thanks for your reply.
I've checked that my phone is set language "VietNamese", so it can't shown "Cancel" button :(

**Comment by kangsojeong** [comment]
me too ... i can't see the cancel button..
