### ISSUE TITLE
Errors during build

### ISSUE THREAD

**Issue by jabirmayar** [chavesgu/images_picker#2]
Cannot build because of the following error.

Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.LuckSiege.PictureSelector:picture_library:v2.5.9.
     Searched in the following locations:
 - https://dl.google.com/dl/android/maven2/com/github/LuckSiege/PictureSelector/picture_library/v2.5.9/picture_library-v2.5.9.pom
       - https://dl.google.com/dl/android/maven2/com/github/LuckSiege/PictureSelector/picture_library/v2.5.9/picture_library-v2.5.9.jar
       - https://jcenter.bintray.com/com/github/LuckSiege/PictureSelector/picture_library/v2.5.9/picture_library-v2.5.9.pom
       - https://jcenter.bintray.com/com/github/LuckSiege/PictureSelector/picture_library/v2.5.9/picture_library-v2.5.9.jar
       - https://developer.huawei.com/repo/com/github/LuckSiege/PictureSelector/picture_library/v2.5.9/picture_library-v2.5.9.pom
       - https://developer.huawei.com/repo/com/github/LuckSiege/PictureSelector/picture_library/v2.5.9/picture_library-v2.5.9.jar
       - https://storage.googleapis.com/download.flutter.io/com/github/LuckSiege/PictureSelector/picture_library/v2.5.9/picture_library-v2.5.9.pom
       - https://storage.googleapis.com/download.flutter.io/com/github/LuckSiege/PictureSelector/picture_library/v2.5.9/picture_library-v2.5.9.jar
     Required by:
         project :app > project :images_picker

**Comment by chavesgu** [comment]
@jabirmayar  hi,your problem look likes error with download url, you can add `maven { url 'https://jitpack.io' }` in your `build.gradle` to test.

**Comment by jabirmayar** [comment]
Sure. I will try and report.
