### ISSUE TITLE
images_picker on iOS displays only Chinese. why not english?  

### ISSUE THREAD

**Issue by zeusbaba** [chavesgu/images_picker#4]
How can I make it support localization? I need at least English by default.  

I have added this to `Info.plist` but no avail...
```
<key>CFBundleLocalizations</key>
        <array>
            <string>en</string>
        </array>
	<key>CFBundleAllowMixedLocalizations</key>
	<true/>
```

**Comment by chavesgu** [comment]
> How can I make it support localization? I need at least English by default.
> 
> I have added this to `Info.plist` but no avail...
> 
> ```
> <key>CFBundleLocalizations</key>
>         <array>
>             <string>en</string>
>         </array>
> 	<key>CFBundleAllowMixedLocalizations</key>
> 	<true/>
> ```

Sorry,because when i test my plugin,I set chinese static.
I will fix it next version.

**Comment by chavesgu** [comment]
@zeusbaba  Hi,update to 0.0.4.
Just set
```
<key>CFBundleAllowMixedLocalizations</key>
<true/>
```
this plugin's language will follow your mobile system setting.

**Comment by zeusbaba** [comment]
Thank you for the quick solution.  
`0.0.4` with `CFBundleAllowMixedLocalizations`  works fine now.
