### ISSUE TITLE
Cant choose the aspect ratio

### ISSUE THREAD

**Issue by Cedriccool** [chavesgu/images_picker#5]
Hello,

And thanks first for this plugin.

I'm trying to force the aspect ratio for cropping at 1:1
I setup the CropOption with aspectRatio:  CropAspectRatio(1, 1) but got a java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer

```
List<Media> res = await ImagesPicker.pick(
    count: 1,
    quality: 0.8,
    maxSize: 500,
      cropOpt: CropOption(
        aspectRatio: CropAspectRatio(1, 1),
        // aspectRatio: CropAspectRatio.wh16x9,
      ),
);
```

The same error happens for CropAspectRatio.wh16x9 and others parameters, except the default one: CropAspectRatio.custom

Is there another way to force the crop as a square?
Thanks

**Comment by chavesgu** [comment]
@Cedriccool I think it's a bug.When I solve it, I will tell you. thank you

**Comment by chavesgu** [comment]
@Cedriccool update to version 0.0.5.It should be ok.

**Comment by Cedriccool** [comment]
Wow perfect and so fast haha, it works great now!
Thank you so much!
