### ISSUE TITLE
Android error, that occurs when picking multiple photos

### ISSUE THREAD

**Issue by nikolajjsj** [chavesgu/images_picker#6]
Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored

This is the function, where the error occurs: 
```dart
Future pickPhoto() async {
    List<Media> _result =
        await ImagesPicker.pick(count: 4, gif: false, maxSize: 5000);

    if (_result != null) {
      setState(() {
        _gif = null;
        _video = null;
        _photos = _result.map((media) => File(media.path)).toList();
      });
    }
  }
```

**Comment by chavesgu** [comment]
> Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
> 
> This is the function, where the error occurs:
> 
> ```dart
> Future pickPhoto() async {
>     List<Media> _result =
>         await ImagesPicker.pick(count: 4, gif: false, maxSize: 5000);
> 
>     if (_result != null) {
>       setState(() {
>         _gif = null;
>         _video = null;
>         _photos = _result.map((media) => File(media.path)).toList();
>       });
>     }
>   }
> ```

hey, bro. I don't understand what you mean, I am not good at android.
May you commit a pr for this issue?

**Comment by chavesgu** [comment]
@nikolajjsj  on my MI 6, this is only warning.

**Comment by nikolajjsj** [comment]
> @nikolajjsj on my MI 6, this is only warning.

I was not able to compile app, because of this warning
