### ISSUE TITLE
图片路径错误

### ISSUE THREAD

**Issue by zichengjiao** [chavesgu/images_picker#7]
相册选择多张图片时，返回的图片路径只有第一条路径正确，其他路劲获取不到图片，如何解决？
`
I/flutter (23480): /data/user/0/com.gongsibao.laowubao/cache/image_picker_dc96c995-70cd-4a73-8aeb-5ce6628b34ee579822762566439927.png

I/flutter (23480): /storage/emulated/0/Android/data/com.gongsibao.laowubao/files/Pictures/IMG_67514222.png

I/flutter (23480): /storage/emulated/0/Android/data/com.gongsibao.laowubao/files/Pictures/IMG_151597422.jpeg
`

**Comment by chavesgu** [comment]
@zichengjiao  可以提供一下调用api的代码片段吗

**Comment by zichengjiao** [comment]
代码：
`
List<Media> res = [];
    if (isCamera == true) {
      res = await ImagesPicker.openCamera();
    } else {
      res = await ImagesPicker.pick(count: 3-_imgUrls.length);
    }
    if (res != null){
      res.forEach((element) {print('~~~本地路径:${element.path}'); });
    }
`
打印结果：
`
I/flutter (23480): /data/user/0/com.gongsibao.laowubao/cache/image_picker_dc96c995-70cd-4a73-8aeb-5ce6628b34ee579822762566439927.png

I/flutter (23480): /storage/emulated/0/Android/data/com.gongsibao.laowubao/files/Pictures/IMG_67514222.png

I/flutter (23480): /storage/emulated/0/Android/data/com.gongsibao.laowubao/files/Pictures/IMG_151597422.jpeg
`

**Comment by chavesgu** [comment]
@zichengjiao  我升级了0.0.6版本  稍后再试试看

**Comment by zichengjiao** [comment]
OK了，谢谢
