### ISSUE TITLE
CocoaPods could not find compatible versions for pod "ZLPhotoBrowser"

### ISSUE THREAD

**Issue by Ttool** [chavesgu/images_picker#74]
Hello,
First thanks a lot for the packeage it is really helpfull.
But from last update to rev 1.2.11 it provide me the following error code when compiling:
_[!] CocoaPods could not find compatible versions for pod "ZLPhotoBrowser":
  In Podfile:
    images_picker (from `.symlinks/plugins/images_picker/ios`) was resolved to 0.0.1, which depends on
      ZLPhotoBrowser (= 4.2.5)

None of your spec sources contain a spec satisfying the dependency: `ZLPhotoBrowser (= 4.2.5)`._

Will it be possible to have your point of view on this error and a way to solve it?
Thanks a lot for your answer.

---- Edit ----
From my side the subject has been  now solved by removing cocoapods and reinstall it:
rm -rf ~/.cocoapods
sudo gem install cocoapods

**Comment by ruo520** [comment]
how deal?

**Comment by ruo520** [comment]
@Ttool

**Comment by jeremylcarter** [comment]
My issue was that my Podfile.lock was not updated. Recreating the lock file or removing it has worked.
