### ISSUE TITLE
Could not find com.github.LuckSiege.PictureSelector:picture_library:v2.5.9.

### ISSUE THREAD

**Issue by Cedriccool** [chavesgu/images_picker#8]
Hi, 

got this error when compiling release: 

Could not resolve all task dependencies for configuration ':app:releaseCompileClasspath'.
[   +1 ms]    > Could not find com.github.LuckSiege.PictureSelector:picture_library:v2.5.9.
[   +9 ms]      Required by:
[   +4 ms]          project :app > com.chavesgu.images_picker:images_picker_release:1.0

Ive tried added "maven { url 'https://jitpack.io' }" to my own build.gradle, but still the same error!

**Comment by chavesgu** [comment]
hi, you don't need to add `maven { url 'https://jitpack.io' }`, because it was be added in the plugin.
I didn't get this error before, I'm from china, can you ping jitpack.io?
I think this isn't plugin's error
