### ISSUE TITLE
Not support set specific Album name (sub-folder)

### ISSUE THREAD

**Issue by JmyW** [chavesgu/images_picker#9]
Hi, thanks for contributing this lib. With this library, I cannot find a way to do saveImageToAlbum and saveVideoToAlbum with an Album name (just sub-folder). Could you help?￼

For example, GallerySaver package can specify album name like "GallerySaver.saveImage(Image.path, albumName: albumName). But I don't like GallerySaver, it somehow has compatibility issue with my app. Will you be possible to support the useful album-name feature?

**Comment by chavesgu** [comment]
now use app name for album name.  I will support your suggest

**Comment by JmyW** [comment]
Thanks!

**Comment by chavesgu** [comment]
> Thanks!

now you can use `0.0.8` version to enjoy `albumName`

**Comment by JmyW** [comment]
Great! Thank you so much!
